import Link from 'next/link';
import { Layout } from '../components/SiteShell';
import { articles, cases, faqs, services, solutions } from '../data/content';
import { whatsappUrl } from '../data/contact';

function WorkflowCard() {
  const steps = [['↗', 'Website enquiry', 'A customer finds your business'], ['◎', 'Lead captured', 'Details are collected clearly'], ['▤', 'CRM', 'Your team sees the next step'], ['◌', 'WhatsApp follow-up', 'A timely, personal response'], ['⌖', 'Booking', 'Move the enquiry forward']];
  return <div className="workflow-card"><div className="workflow-top"><span className="workflow-label">A connected customer journey</span><span className="workflow-example">Example workflow</span></div><div className="workflow-flow">{steps.map(([icon, name, detail], index) => <div key={name}><div className={`workflow-step ${index === 3 ? 'active' : ''}`}><span className="workflow-icon" aria-hidden>{icon}</span><span className="workflow-step-name">{name}</span><span className="workflow-step-detail">{detail}</span></div>{index < steps.length - 1 && <div className="workflow-link" />}</div>)}</div><div className="workflow-foot"><span>Designed around your business</span><span>01 — 05</span></div></div>;
}

function SystemPanel() {
  const rows = [['01', 'Website enquiry', 'Captured'], ['02', 'Lead record', 'Organized'], ['03', 'WhatsApp follow-up', 'Ready'], ['04', 'Booking confirmed', 'Next step']];
  return <div className="system-panel"><div className="system-panel-top"><span>Customer journey overview</span><span className="system-status">Example system</span></div><div className="system-body"><div className="system-list">{rows.map(([n, title, status], i) => <div className={`system-row ${i === 2 ? 'current' : ''}`} key={n}><span className="system-row-number">{n}</span><span className="system-row-title">{title}</span><span className="system-row-meta">{status}</span></div>)}</div><div className="system-side"><div className="system-mini"><div className="system-mini-label">Next action</div><div className="system-mini-value">Follow up</div><span className="system-mini-chip">WhatsApp</span></div><div className="system-mini"><div className="system-mini-label">Visibility</div><div className="system-mini-value">One clear view</div><span className="system-mini-chip">CRM + activity</span></div></div></div></div>;
}

function ProductMock() {
  return <div className="product-mock" role="img" aria-label="Example automotive product catalogue interface"><div className="product-bar"><span className="product-brand">AUTOMOTIVE PRODUCT CATALOGUE</span><span className="product-basket">Illustrative UI</span></div><div className="product-grid">{['◉', '◈', '◇'].map((icon, i) => <div className="product-tile" key={icon}><div className="product-picture">{icon}</div><div className="product-line"/><div className="product-line short"/></div>)}</div></div>;
}

export default function Home() {
  const featured = cases.slice(0, 3);
  return <Layout><main>
    <section className="home-hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">Digital Solutions &amp; Automation</p><h1 className="hero-title">Better systems for businesses that want to move faster.</h1><p className="hero-description">Axivy builds websites, customer systems and practical automation that help businesses capture more enquiries, respond faster and operate more efficiently.</p><div className="hero-actions"><Link className="btn btn-primary" href="/contact">Let's Talk <span aria-hidden>↗</span></Link><Link className="btn btn-secondary" href="/case-studies">View Our Work <span aria-hidden>↗</span></Link></div><p className="hero-note"><span className="note-dot"/> Doha based. Built for practical business needs.</p></div><WorkflowCard/></div></section>

    <div className="capability-strip"><div className="shell capability-inner"><span className="capability-label">One partner for connected systems</span><div className="capability-list">{['Websites', 'CRM', 'WhatsApp', 'Automation', 'AI', 'Analytics'].map(label => <span className="capability-item" key={label}>{label}</span>)}</div></div></div>

    <section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">The problem</p><h2 className="section-heading">Good businesses lose opportunities when their systems don't keep up.</h2></div><p className="section-copy">Scattered tools and inconsistent follow-up make it harder to give customers a clear, timely experience.</p></div><div className="problem-grid">{[['01', 'Missed enquiries', 'Potential customers reach out, but follow-up can slip.'], ['02', 'Manual follow-ups', 'Teams repeat simple tasks instead of focusing on customers.'], ['03', 'Scattered information', 'Customer details sit across chats, sheets and phones.'], ['04', 'No clear visibility', 'It is hard to see what happens after the first message.']].map(([n, title, copy]) => <article className="problem-card" key={n}><span className="problem-number">{n}</span><h3 className="problem-title">{title}</h3><p className="problem-description">{copy}</p></article>)}</div></div></section>

    <section className="section-tight"><div className="shell"><div className="section-head"><div><p className="eyebrow">Services</p><h2 className="section-heading">What Axivy builds</h2></div><p className="section-copy">Practical digital tools for your customer journey and the work behind it.</p></div><div className="service-grid">{services.map(([icon, title, copy], index) => <article className="service-card" key={title}><div className="service-card-top"><span className="service-number">{String(index + 1).padStart(2, '0')}</span><span className="service-icon" aria-hidden>{icon}</span></div><h3 className="service-title">{title}</h3><p className="service-description">{copy}</p><Link className="service-arrow" href="/services" aria-label={`Explore ${title}`}>Explore <span aria-hidden>→</span></Link></article>)}</div></div></section>

    <section className="section feature-section"><div className="shell feature-grid"><div><p className="eyebrow">Connected systems</p><h2 className="feature-title">One customer journey. One connected system.</h2><p className="feature-copy">Bring the website, customer record and follow-up process together. Your team can see what happened and what to do next.</p><div className="feature-path" aria-label="Website to analytics workflow"><span>Website</span><i>→</i><span>Lead</span><i>→</i><span>CRM</span><i>→</i><span>WhatsApp</span><i>→</i><span>Booking</span><i>→</i><span>Analytics</span></div><Link className="btn btn-primary" href="/services" style={{marginTop: 22}}>Explore connected solutions <span aria-hidden>↗</span></Link></div><SystemPanel/></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">Industries</p><h2 className="section-heading">Built around the way your business works.</h2></div><Link href="/solutions" className="work-link">Explore solutions <span aria-hidden>→</span></Link></div><div className="industry-grid">{solutions.map(([name, copy]) => <Link className="industry-item" href="/solutions" key={name}><span><h3 className="industry-name">{name}</h3><p className="industry-description">{copy}</p></span><span className="industry-arrow" aria-hidden>↗</span></Link>)}</div></div></section>

    <section className="section-tight"><div className="shell"><div className="section-head"><div><p className="eyebrow">Selected work</p><h2 className="section-heading">Made to solve real business needs.</h2></div><Link href="/case-studies" className="work-link">All case studies <span aria-hidden>→</span></Link></div><div className="work-grid"><article className="work-card work-card-primary"><div className="work-visual"><ProductMock/></div><div className="work-info"><div className="work-meta"><span>Automotive commerce</span><span className="work-tag">Real project</span></div><h3 className="work-title">{featured[0][1]}</h3><p className="work-description">Online product catalogue and WhatsApp ordering, connected through a delivery-based customer journey.</p><Link className="work-link" href={`/case-studies/${featured[0][0]}`}>View case study <span aria-hidden>→</span></Link></div></article><article className="work-card"><div className="work-visual sage"><div className="founder-initials" aria-hidden>S</div><span className="work-example">Business website</span></div><div className="work-info"><div className="work-meta"><span>Professional website</span><span className="work-tag">Web project</span></div><h3 className="work-title">{featured[1][1]}</h3><p className="work-description">A clear, professional business presence online.</p><Link className="work-link" href={`/case-studies/${featured[1][0]}`}>View project <span aria-hidden>→</span></Link></div></article><article className="work-card"><div className="work-visual dark"><div className="system-mini" style={{width: '72%'}}><div className="system-mini-label">Concept / Demo</div><div className="system-mini-value">Workshop enquiries</div><span className="system-mini-chip">Booking flow →</span></div></div><div className="work-info"><div className="work-meta"><span>Business automation</span><span className="work-tag">Concept / Demo</span></div><h3 className="work-title">{featured[2][1]}</h3><p className="work-description">A concept for bringing enquiries, bookings and follow-up together.</p><Link className="work-link" href={`/case-studies/${featured[2][0]}`}>View concept <span aria-hidden>→</span></Link></div></article></div></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">How we work</p><h2 className="section-heading">A clear path from idea to launch.</h2></div><Link href="/process" className="work-link">Our process <span aria-hidden>→</span></Link></div><div className="process-grid">{[['01', 'Discover', 'Understand your business and customer journey.'], ['02', 'Plan', 'Set the scope, workflow and priorities.'], ['03', 'Build', 'Design and develop the right solution.'], ['04', 'Connect', 'Bring the useful tools and systems together.'], ['05', 'Launch', 'Test, deploy and support your team.'], ['06', 'Improve', 'Review what works and refine the system.']].map(([number, title, copy]) => <article className="process-step" key={number}><span className="process-number">{number}</span><h3 className="process-title">{title}</h3><p className="process-copy">{copy}</p></article>)}</div></div></section>

    <section className="section-tight"><div className="shell about-grid"><div className="founder-mark"><span className="founder-initials" aria-hidden>MM</span><div className="founder-caption"><strong>Munir Uddin Mahbub</strong><span>Founder &amp; Full-Stack Developer</span></div></div><div><p className="eyebrow">About Axivy</p><h2 className="section-heading">Technology built around real business problems.</h2><p className="section-copy">Axivy brings full-stack development and practical problem solving to websites, business automation, AI and software systems. We start by understanding how your business works, then build what helps.</p><Link href="/about" className="work-link" style={{marginTop: 18}}>More about Axivy <span aria-hidden>→</span></Link></div></div></section>

    <section className="section-tight"><div className="shell"><div className="section-head"><div><p className="eyebrow">Insights</p><h2 className="section-heading">Ideas for better business systems.</h2></div><Link href="/insights" className="work-link">All insights <span aria-hidden>→</span></Link></div><div className="insight-grid">{articles.slice(0, 3).map(([slug, title]) => <Link href={`/insights/${slug}`} className="insight-card" key={slug}><span className="insight-category">Business systems</span><h3 className="insight-title">{title}</h3><span className="insight-read">Read insight <span aria-hidden>→</span></span></Link>)}</div></div></section>

    <section className="section-tight"><div className="shell"><p className="eyebrow">Common questions</p><h2 className="section-heading">A few things businesses often ask.</h2><div className="faq-grid">{faqs.map(([question, answer]) => <details className="faq-item" key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>

    <section className="final-cta"><div className="shell cta-grid"><div><p className="eyebrow">Start a conversation</p><h2 className="cta-title">Have a business problem worth solving?</h2><p className="cta-copy">Tell us what is slowing your business down. We'll help you identify a practical digital or automation solution.</p></div><div className="cta-actions"><Link className="btn btn-primary" href="/contact">Let's Talk <span aria-hidden>↗</span></Link><a className="btn btn-secondary" href={whatsappUrl("Hi Axivy, I'd like to discuss a business solution.")} target="_blank" rel="noreferrer">WhatsApp <span aria-hidden>↗</span></a><span className="cta-phone">+974 7108 3700</span></div></div></section>
  </main></Layout>;
}
