'use client';
import Link from 'next/link';
import { useState } from 'react';
import { AXIVY_LOCATION, AXIVY_PHONE, whatsappUrl } from '../data/contact';

const nav=[['Services','/services'],['Solutions','/solutions'],['Case Studies','/case-studies'],['Process','/process'],['About','/about'],['Insights','/insights']];
export function Header(){const [open,setOpen]=useState(false);return <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-slate-50/90 backdrop-blur"><div className="shell flex h-[72px] items-center justify-between"><Link href="/" className="text-xl font-extrabold tracking-[-.06em] text-[#0b1220]">Axivy<span className="text-blue-600">.</span></Link><nav className="hidden gap-7 text-sm font-semibold text-slate-600 lg:flex">{nav.map(([a,h])=><Link className="hover:text-blue-600" href={h} key={h}>{a}</Link>)}</nav><div className="hidden lg:block"><Link className="btn btn-primary" href="/contact">Let's Talk <span>→</span></Link></div><button aria-label="Open navigation" onClick={()=>setOpen(!open)} className="rounded-md border border-slate-300 p-2 lg:hidden">☰</button></div>{open&&<div className="border-t border-slate-200 bg-white px-5 py-5 lg:hidden">{nav.map(([a,h])=><Link onClick={()=>setOpen(false)} href={h} className="block py-3 text-base font-semibold" key={h}>{a}</Link>)}<Link href="/contact" className="btn btn-primary mt-3">Let's Talk →</Link></div>}</header>}
export function Footer(){return <footer className="bg-[#0b1220] py-14 text-slate-300"><div className="shell grid gap-10 md:grid-cols-[1.4fr_1fr_1fr]"><div><p className="text-2xl font-extrabold text-white">Axivy<span className="text-cyan-400">.</span></p><p className="mt-4 max-w-xs leading-7">Digital Solutions &amp; Automation</p><p className="mt-4 text-sm">{AXIVY_LOCATION}</p><p className="mt-2 text-sm">WhatsApp: {AXIVY_PHONE}</p><a className="btn mt-5 border border-slate-600 text-white hover:bg-white/10" href={whatsappUrl("Hi Axivy, I'd like to discuss a business solution.")} target="_blank" rel="noreferrer">Chat on WhatsApp <span aria-hidden>↗</span></a></div><div><p className="mb-4 font-bold text-white">Navigate</p>{[...nav,['Contact','/contact']].map(([a,h])=><Link href={h} className="mb-2 block text-sm hover:text-white" key={h}>{a}</Link>)}</div><div><p className="mb-4 font-bold text-white">Based in Qatar</p><p className="text-sm leading-6">Supporting businesses in Qatar and working with teams remotely.</p><div className="mt-5 flex gap-4 text-sm"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div></div><div className="shell mt-12 border-t border-slate-700 pt-6 text-xs text-slate-500">© {new Date().getFullYear()} Axivy. All rights reserved.</div></footer>}
export function WhatsAppFloat(){return <a href={whatsappUrl("Hi Axivy, I'd like to discuss a business solution.")} target="_blank" rel="noreferrer" aria-label="Chat with Axivy on WhatsApp" className="fixed bottom-5 right-4 z-40 flex items-center gap-2 rounded-full bg-emerald-600 px-4 py-3 text-sm font-bold text-white shadow-lg transition hover:bg-emerald-700 md:hidden"><span aria-hidden>◉</span><span>WhatsApp</span></a>}
export function Layout({children}){return <><Header/>{children}<Footer/><WhatsAppFloat/></>}
